// 运营台中文文案字典。
// 用途:集中管理跨页面复用、且被测试断言引用的文案,组件与测试同源引用以避免漂移。
// 仅在单页面出现一次的文案可直接内联中文,不必都收进来。

// 验证链 / 接管台命令名 → 中文动作名。
// 命令名本身(key)是后端契约,仍作为按钮副标题(mono 芯片)展示并参与无障碍可达名。
export const OPS_COMMAND_LABELS = {
  'create-market': '创建市场',
  'open-market': '开盘',
  'freeze-market': '冻结市场',
  'resolve-market': '结算市场',
  'cancel-market': '取消市场',
  'recover-command': '恢复指令链',
  'replay-projection': '重放投影',
  'reconcile-bet': '对账注单',
  sync: '同步链状态',
  'reconcile-backlog': '对账积压',
  pause: '暂停调度',
  unpause: '恢复调度',
} as const

export type OpsCommandName = keyof typeof OPS_COMMAND_LABELS

export function opsCommandLabel(command: string): string {
  return (OPS_COMMAND_LABELS as Record<string, string>)[command] ?? command
}

export const opsCopy = {
  // 顶部导航
  nav: {
    overview: '总览',
    propositions: '命题',
    responses: '响应',
    rewards: '奖励',
    audit: '审计',
    health: '健康度',
    takeover: '接管台',
  },
  // 面包屑
  crumbs: {
    ops: '运营',
    overview: '总览',
    propositions: '命题',
    responses: '响应',
    rewards: '奖励',
    audit: '审计',
    health: '健康度',
    takeover: '接管台',
    respondents: '答题人',
    notFound: '未找到',
  },
  // 工作区头部
  shell: {
    eyebrow: 'ARENA 内部工作区',
    title: '运营工作台',
    navAria: '运营工作台导航',
    notFoundTitle: '工作区未找到',
    notFoundBody: '请使用上方导航返回到已有的运营工作区入口。',
  },
  // 通用动作
  actions: {
    refresh: '刷新',
    retry: '重试',
    previous: '上一页',
    next: '下一页',
    clearSelection: '清空选择',
    selectVisible: '全选本页',
    confirm: '确认',
    cancel: '取消',
    working: '处理中…',
  },
  // 通用筛选 label / 选项
  filters: {
    all: '全部',
    status: '状态',
    category: '类别',
    market: '市场',
    search: '搜索',
    sort: '排序',
    direction: '方向',
    pageSize: '每页',
    workflow: '流转',
    review: '复核',
    proposition: '命题',
    enabled: '已开启',
    disabled: '已关闭',
  },
  // 通用空 / 错 / 加载
  states: {
    loading: '加载中',
    notFound: '未找到',
    permissionDenied: '你没有访问该运营视图的权限。',
    authExpired: '登录态已失效,请重新登录后继续。',
    networkError: '无法连接运营接口,请检查后端连接后重试。',
  },
  // 共享组件文案(列表标题 / 工作区跳转链接 / 审计线索)
  shared: {
    auditThread: '审计线索',
    commands: '命令',
    blockingDependencies: '阻塞依赖',
    operatorActions: '运营动作',
    loadingAria: '加载中',
    openProposition: '打开命题',
    openReward: '打开奖励',
    openResponse: '打开响应',
    openRespondent: '打开答题人',
    openTakeover: '打开接管台',
    openHealth: '打开健康度',
  },
  // 队列页共享(分页 / 选择)
  queue: {
    selectedOnPage: (count: number) => `选中本页:${count}`,
    showingRange: (from: number, to: number, total: number) => `显示第 ${from}-${to} 条,共 ${total} 条`,
  },
  // 响应复核队列页
  responses: {
    filters: {
      workflow: '流转状态',
      review: '复核状态',
      proposition: '命题',
      propositionPlaceholder: 'propositionId',
      claimedBy: '认领人',
      claimedByPlaceholder: '运营用户 ID',
      claimStaleOnly: '仅看超时认领',
      search: '搜索',
      searchPlaceholder: '响应 / 命题 / 用户',
      sort: '排序',
      direction: '方向',
      pageSize: '每页',
    },
    queueTitle: '响应复核队列',
    empty: '当前没有待复核的响应。',
    selectAllAria: '全选本页响应',
    selectResponseAria: (id: string) => `选择响应 ${id}`,
    batchClaim: '批量认领',
    batchRelease: '批量释放',
    batchReview: '批量复核',
    stale: '超时',
    table: {
      select: '选择',
      proposition: '命题',
      response: '响应',
      user: '用户',
      review: '复核',
      workflow: '流转',
      submitted: '提交时间',
    },
    detailTitle: '响应详情',
    detailEmpty: '从队列中选择一条响应以查看详情。',
    notFound: '未找到该响应。',
    kv: {
      response: '响应',
      proposition: '命题',
      user: '用户',
      workflow: '流转',
      review: '复核',
      submitted: '提交时间',
    },
    claim: '认领',
    release: '释放',
    review: '复核',
    flags: '标记',
    reasonCodes: '原因码',
    dialogClaimTitle: '认领响应',
    dialogReleaseTitle: '释放响应',
    dialogReviewTitle: '复核响应',
    responseIdLabel: (id: string) => `响应 ID:${id}`,
    claimedMsg: '响应已认领。',
    releasedMsg: '响应已释放。',
    reviewedMsg: '响应已送审。',
    batchClaimTitle: '批量认领响应复核',
    batchReleaseTitle: '批量释放响应复核',
    batchReviewTitle: '批量复核响应',
    selectedCount: (count: number) => `已选 ${count} 条响应`,
    actionLabels: {
      claim: '认领',
      release: '释放',
      review: '复核',
    },
    batchResultOk: (action: string, count: number) => `批量${action}完成,处理 ${count} 条响应。`,
    batchResultFail: (action: string, count: number) => `批量${action}完成,其中 ${count} 条失败。`,
  },
  // 命题审核 / 列表页
  propositions: {
    filters: {
      reviewQueueOnly: '仅看复核队列',
      status: '状态',
      category: '类别',
      market: '市场',
      search: '搜索',
      searchPlaceholder: '标题 / 命题 ID',
      sort: '排序',
      direction: '方向',
      pageSize: '每页',
    },
    marketEnabledOption: '已开启',
    marketDisabledOption: '已关闭',
    queueTitle: '命题复核队列',
    listTitle: '命题列表',
    empty: '没有符合当前筛选条件的命题。',
    selectAllAria: '全选本页命题',
    selectVisible: '全选本页',
    selectPropositionAria: (id: string) => `选择命题 ${id}`,
    batchApprove: '批量通过',
    batchReject: '批量驳回',
    table: {
      select: '选择',
      proposition: '命题',
      category: '类别',
      submission: '提交状态',
      status: '状态',
      samples: '有效样本',
      pendingReview: '待复核',
    },
    inlineMetric: {
      effectiveSample: '有效样本',
      pendingReview: '待复核',
      sampleShortage: '样本缺口',
      marketEnabled: '市场开关',
    },
    dialogApproveTitle: '批量通过命题',
    dialogRejectTitle: '批量驳回命题',
    selectedCount: (count: number) => `已选 ${count} 条命题`,
    reasonLabel: '复核原因',
    approveSuccess: '批量通过完成。',
    rejectSuccess: '批量驳回完成。',
    actionLabels: {
      approve: '通过',
      reject: '驳回',
    },
    batchResultOk: (action: string, count: number) => `批量${action}完成,处理 ${count} 条命题。`,
    batchResultFail: (action: string, count: number) => `批量${action}完成,其中 ${count} 条失败。`,
    queueNotesTitle: '队列说明',
    queueNotesBody:
      '复核队列模式复用后端复核队列契约,普通列表则读取更宽口径的内部命题索引。',
  },
  // 命题详情页
  propositionDetail: {
    actions: {
      approve: '通过',
      reject: '驳回',
      freeze: '紧急冻结',
    },
    dialogTitles: {
      approve: '通过命题',
      reject: '驳回命题',
      freeze: '紧急冻结命题',
    },
    decisionReasonLabel: '决策原因',
    propositionIdLabel: (id: string) => `命题 ID:${id}`,
    dialogCompleted: (title: string) => `${title}已完成。`,
    notFound: '未找到目标命题。',
    working: '处理中…',
    none: '无',
    unset: '未设置',
    pending: '待定',
    marketEnabledOn: '已开启',
    marketEnabledOff: '已关闭',
    lifecycle: {
      title: '基础信息与生命周期',
      category: '类别',
      createdAt: '创建时间',
      publishedAt: '发布时间',
      liveAt: '上线时间',
      frozenAt: '冻结时间',
      settledAt: '结算时间',
      marketEnabled: '市场开关',
      submissionNote: '提交备注',
    },
    metrics: {
      effectiveSample: '有效样本',
      pendingReview: '待复核',
      finalizedReviews: '已定档复核',
      rewardEntries: '奖励条目',
    },
    stats: {
      closureReadiness: '收口就绪',
      dispatchCoverage: '派发覆盖',
      revealSettlement: '揭晓 / 结算',
      resultKind: '结果类型',
      reviewInvalidRate: '复核无效率',
      reviewAnomalyRate: '复核异常率',
    },
    validationChain: {
      title: '验证链状态',
      driftReason: '漂移原因',
      chainState: '链上状态',
      marketStatus: '市场状态',
      operatorSummary: '运营摘要',
      driftGuidance: '漂移处置指引',
      plannedCommands: '计划命令',
      operatorActions: '运营动作',
    },
    rehearsal: {
      title: '验证演练',
      status: '状态',
      targetOutcome: '目标结果',
      runbook: '操作手册',
      latestCheckpoint: '最近检查点',
      nextCommands: '后续命令',
      blockingReasons: '阻塞原因',
      commands: '命令',
      evidence: '证据',
    },
    evidence: {
      title: '证据中心',
      exportJson: '导出命题 JSON',
      exportCsv: '导出命题 CSV',
      downloadReport: '下载报告',
      downloadBundleJson: '下载证据包 JSON',
      previewBundle: '预览证据包',
      downloadCheckpointsJson: '下载检查点 JSON',
      downloadCheckpointsCsv: '下载检查点 CSV',
      auditTimeline: '审计时间线',
      auditTimelineEmpty: '暂无命题审计事件。',
      rewardAudit: '奖励审计',
      rewardAuditEmpty: '暂无奖励审计事件。',
      chainActivity: '验证链活动',
      chainActivityEmpty: '暂无验证链活动。',
      bundlePreview: '证据包预览',
      bundleKv: {
        proposition: '命题',
        runtimeReadiness: '运行时就绪度',
        runtimeBlockers: '运行时阻塞',
        validationSync: '验证同步',
        validationAlerts: '验证告警',
        auditEvents: '审计事件',
        rewardAudits: '奖励审计',
        checkpoints: '检查点',
      },
      runtimeBlockersList: '运行时阻塞项',
      runtimeOperatorActions: '运行时运营动作',
      validationAlertReasons: '验证告警原因',
    },
    responseSubQueue: {
      title: '响应子队列',
      empty: '当前命题暂无排队中的响应。',
      response: '响应',
      user: '用户',
      workflow: '流转',
      submitted: '提交时间',
    },
    reward: {
      title: '奖励跟进',
      pendingAmount: '待发放金额',
      finalAmount: '最终金额',
      pendingEntries: '待处理条目',
      latestEvent: (action: string, date: string) => `最近奖励事件:${action} / ${date}`,
      openWorkspace: '打开奖励工作区',
    },
    checkpointForm: {
      title: '记录演练检查点',
      hint: '当运营完成某个演练步骤时,在此录入人工证据。',
      step: '检查点步骤',
      status: '检查点状态',
      txHash: '检查点交易哈希',
      blockNumber: '检查点区块号',
      reason: '检查点原因',
      note: '检查点备注',
      evidence: '检查点证据',
      evidencePlaceholder: '每行一条证据',
      submit: '记录检查点',
      recorded: '检查点已记录',
      receiptStep: (step: string) => `步骤:${step}`,
      receiptStatus: (status: string) => `状态:${status}`,
      receiptRecordedAt: (at: string) => `记录时间:${at}`,
      recentTitle: '近期检查点',
      recentEmpty: '尚未记录任何演练检查点。',
      tableStep: '步骤',
      tableStatus: '状态',
      tableReason: '原因',
      tableRecorded: '记录时间',
      reasonRequired: '请填写检查点原因。',
      blockNumberInvalid: '检查点区块号必须为 0 或更大。',
    },
  },
  // 奖励审核工作台
  rewards: {
    filters: {
      proposition: '命题',
      propositionPlaceholder: 'propositionId',
      response: '响应',
      responsePlaceholder: 'responseId',
      user: '用户',
      userPlaceholder: 'userId',
      status: '状态',
      source: '来源',
      search: '搜索',
      searchPlaceholder: 'ledger / 命题 / 响应 / 用户',
      sort: '排序',
      direction: '方向',
      pageSize: '每页',
    },
    sourceResponse: '响应',
    queueTitle: '奖励审核工作台',
    empty: '当前没有待审核的奖励条目。',
    selectAllAria: '全选本页奖励',
    selectVisible: '全选本页',
    selectRewardAria: (id: string) => `选择奖励 ${id}`,
    batchRetrigger: '批量重发',
    table: {
      select: '选择',
      proposition: '命题',
      response: '响应',
      user: '用户',
      ledgerStatus: '账目状态',
      review: '复核',
      amount: '金额',
      version: '版本',
      created: '创建时间',
      finalized: '定档时间',
    },
    noReview: '无',
    detailTitle: '账目详情',
    detailEmpty: '从队列中选择一条账目以查看详情。',
    notFound: '未找到该 ledger。',
    payoutTitle: '发放详情',
    noPayout: '该账目尚未创建发放记录。',
    kv: {
      ledger: '账目',
      proposition: '命题',
      response: '响应',
      user: '用户',
      review: '复核',
      payoutStatus: '发放状态',
      payoutMethod: '发放方式',
      payoutAmount: '发放金额',
      payoutDestination: '到账地址',
      payoutRequestedAt: '申请时间',
      payoutApprovedAt: '审核时间',
      payoutCompletedAt: '到账时间',
      payoutFailedAt: '失败时间',
      payoutRetryCount: '重试次数',
      payoutTxHash: '执行哈希',
      payoutError: '失败原因',
    },
    retriggerCmdLabel: '重发结算',
    approveCmdLabel: '审核发放',
    startExecutionCmdLabel: '开始执行',
    completeCmdLabel: '标记到账',
    confirmExecutionCmdLabel: '确认到账',
    failCmdLabel: '登记失败',
    auditTitle: '奖励审计事件',
    auditEmpty: '该条目暂无奖励审计事件。',
    chainNoReview: '无复核',
    chainItem: (version: number, review: string, created: string) => `v${version} / ${review} / 创建于 ${created}`,
    dialogRetriggerTitle: '重发奖励复核结算',
    dialogApproveTitle: '审核奖励发放',
    dialogStartExecutionTitle: '开始执行奖励发放',
    dialogCompleteTitle: '确认奖励到账',
    dialogConfirmExecutionTitle: '按已记录执行哈希确认到账',
    dialogFailTitle: '登记奖励发放失败',
    dialogBatchTitle: '批量重发奖励复核结算',
    ledgerIdLabel: (id: string) => `账目 ID:${id}`,
    selectedCount: (count: number) => `已选 ${count} 条奖励`,
    retryReasonLabel: '重试原因',
    payoutReasonLabel: '处置原因',
    payoutExecutionTxHashLabel: '执行哈希',
    payoutExternalReferenceLabel: '批次 / 外部单号',
    payoutErrorCodeLabel: '错误码',
    payoutErrorMessageLabel: '错误说明',
    retriggerSuccess: '已重发奖励结算。',
    approveSuccess: '奖励发放已审核。',
    startExecutionSuccess: '奖励发放已进入执行。',
    completeSuccess: '奖励发放已标记到账。',
    confirmExecutionSuccess: '已按记录的执行哈希确认奖励到账。',
    failSuccess: '奖励发放失败已登记。',
    batchSuccess: '批量重发完成。',
    batchResultOk: (count: number) => `批量重发完成,处理 ${count} 条奖励。`,
    batchResultFail: (count: number) => `批量重发完成,其中 ${count} 条失败。`,
  },
  // 总览页
  overview: {
    // 全局待办指标卡
    propositionsAwaitingReview: '待复核命题',
    propositionsAwaitingReviewDetail: '等待运营决策的优先命题',
    responsesAwaitingReview: '待复核响应',
    responsesAwaitingReviewDetail: '正在排队等待审核与分流的响应',
    pendingRewards: '待发放奖励',
    pendingRewardsDetail: '仍在等待发放或处置的奖励条目',
    healthAlerts: '健康度告警',
    healthAlertsDetail: '异常、样本不足与漂移信号',
    releaseReadiness: '发布就绪度',
    validationRehearsal: '验证演练',
    validationRehearsalDetail: '跟踪演练状态与阻塞检查点',
    loading: '加载中',
    // 个人效率指标卡
    todayThroughput: '今日吞吐',
    todayThroughputLoading: '正在加载近期审计日志',
    todayThroughputDetail: (count: number) => `今日已记录 ${count} 次操作`,
    myActiveReviewLoad: '我的在办复核',
    myActiveReviewLoading: '正在加载已认领复核',
    myActiveReviewDetail: (count: number) => `已认领 ${count} 条复核`,
    claimSlaBreaches: '认领超时',
    claimSlaLoading: '正在加载认领积压',
    claimSlaNoOverdue: '无超时认领',
    claimSlaOldestOverdue: (duration: string) => `最久已超时 ${duration}`,
    // 最高优先级泳道
    highestPriorityLane: '当前最高优先级泳道',
    noActivePriorityLane: '当前暂无活跃的优先级泳道。',
    blockers: '阻塞项',
    operatorActions: '运营动作',
    latestEvidence: (action: string, reason: string) => `最近证据:${action} / ${reason}`,
    // 侧栏快捷入口
    quickLinks: '快捷入口',
    reviewPropositions: '复核命题',
    claimStaleResponses: '认领超时响应',
    checkPendingRewards: '查看待发放奖励',
    openAuditLog: '打开审计日志',
    viewMyAuditTrail: '查看我的审计轨迹',
    openTakeoverDesk: '打开接管台',
    // 最近操作
    myRecentOperations: '我的近期操作',
    noRecentOperations: '本工作站暂无近期操作记录。',
    openFullAuditTrail: '打开完整审计轨迹',
    toneSuccess: '成功',
    toneError: '失败',
  },
  // 健康度工作台
  health: {
    // 运营摘要面板
    summaryTitle: '运营摘要',
    refreshQueues: '刷新队列',
    refreshChain: '刷新链状态',
    refreshContract: '刷新契约',
    summaryEmpty: '运营摘要暂不可用。',
    summaryKv: {
      status: '状态',
      currentLane: '当前泳道',
      focusArea: '关注领域',
      summary: '摘要',
      latestEvidence: '最近证据',
    },
    laneRuntimeContract: '运行时契约',
    laneValidationChain: '验证链',
    laneNone: '无',
    none: '无',
    blockers: '阻塞项',
    operatorActions: '运营动作',
    latestEvidenceValue: (action: string, reason: string) => `${action} / ${reason}`,
    currentAuditThread: '当前审计线索',
    // 验证链健康面板
    chainHealthTitle: '验证链健康',
    chainHealthEmpty: '验证链健康数据暂不可用。',
    metrics: {
      recentAlerts: '近期告警',
      duplicateRows: '重复行',
      recentEvents: '近期事件',
      unsyncedBacklog: '未同步积压',
    },
    chainKv: {
      syncStatus: '同步状态',
      stream: '事件流',
      lastBlock: '最新区块',
      lastTx: '最新交易',
      lastLogIndex: '最新日志索引',
      cursorUpdated: '游标更新于',
      schedulerWorker: '调度 worker',
    },
    dependencyActions: '依赖动作',
    schedulerWorkerTitle: '调度 worker',
    schedulerWorkerEmpty: '调度 worker 详情暂不可用。',
    schedulerWorkerKv: {
      checked: '检查于',
      started: '启动于',
      lastSeen: '最近在线',
      lastJob: '最近任务',
      lastProcessed: '最近处理',
      lastError: '最近错误',
    },
    workerOperatorActions: 'worker 运营动作',
    eventLedgerTitle: '事件账本 / 告警',
    recentAlertsTitle: '近期告警',
    recentAlertsEmpty: '暂无近期告警。',
    duplicateRowsTitle: '重复行',
    duplicateRowsEmpty: '暂无重复事件行。',
    duplicateRowPrimary: (txHash: string, logIndex: string) => `${txHash} / 日志 ${logIndex}`,
    duplicateRowSecondary: (chainId: string, count: string) => `链 ${chainId} / 重复 ${count}`,
    recentEventsTitle: '近期事件',
    recentEventsEmpty: '暂无近期链上事件。',
    recentEventSecondary: (block: string, txHash: string, processedAt: string) => `区块 ${block} / 交易 ${txHash} / ${processedAt}`,
    latestProjectionTitle: '最新投影',
    projectionKv: {
      latestMarket: '最新市场',
      marketStatus: '市场状态',
      latestBet: '最新注单',
      betSettlement: '注单结算',
      marketSynced: '市场同步于',
      betSynced: '注单同步于',
    },
    recentFailuresTitle: '近期失败',
    recentFailuresEmpty: '暂无近期失败。',
    stalePayoutBadge: '结算滞留',
    stalePayoutDetail: (propositionId: string, unclaimedBetCount: string) => `命题 ${propositionId} / 未认领注单 ${unclaimedBetCount}`,
    openProposition: '打开命题',
    openTakeover: '打开接管台',
    // 未同步积压操作
    backlogActionsTitle: '未同步积压操作',
    selectAllBacklogAria: '全选本页积压注单',
    selectVisible: '全选本页',
    clearSelection: '清空选择',
    batchReconcile: '批量对账',
    selectedInBacklog: (count: number) => `已选积压:${count}`,
    backlogBadge: '未同步积压',
    selectBacklogAria: (betId: string) => `选择积压注单 ${betId}`,
    select: '选择',
    backlogItemDetail: (marketId: string, userId: string, ageSeconds: number) => `市场 ${marketId} / 用户 ${userId} / 已积压 ${ageSeconds} 秒`,
    reconcileBet: '对账注单',
    // 单笔 reconcile 弹窗
    reconcileTitle: '执行单笔对账',
    reconcileDescription: (marketId: string, userId: string) => `市场 ${marketId} / 用户 ${userId}`,
    reconcileReasonLabel: '处置原因',
    reconcileSuccess: '已触发注单对账。',
    // 队列重入队弹窗
    requeueTitle: '重入队失败任务',
    requeueDescription: (queueName: string) => `队列:${queueName}`,
    requeueSuccess: '失败任务已重入队。',
    // 批量 reconcile 弹窗
    batchReconcileTitle: '批量对账未同步积压',
    batchReconcileDescription: (count: number) => `已选 ${count} 条积压注单`,
    batchReconcileReasonLabel: '处置原因',
    batchReconcileSubmitted: '批量对账已提交。',
    batchReconcileResultOk: (count: number) => `批量对账完成,处理 ${count} 条积压注单。`,
    batchReconcileResultFail: (count: number) => `批量对账完成,其中 ${count} 条失败。`,
  },
  // 队列总览面板
  queueOverview: {
    title: '队列总览',
    paused: '已暂停',
    requeueFailed: '重入队失败',
    table: {
      queue: '队列',
      status: '状态',
      waiting: '等待',
      active: '处理中',
      delayed: '延迟',
      completed: '已完成',
      failed: '失败',
      actions: '操作',
    },
  },
  // 运行时契约面板
  runtimeContract: {
    title: '运行时就绪度 / 契约',
    readinessKv: {
      readiness: '就绪度',
      chain: '链',
      validationEnv: '验证环境',
      runbook: '操作手册',
    },
    requiredEnvKeys: '必填环境变量',
    optionalEnvKeys: '可选环境变量',
    readinessPreflight: '就绪度预检',
    envKeys: '环境变量',
    commands: '命令',
    contractKv: {
      releaseReadiness: '发布就绪度',
      gates: '关卡',
      rehearsal: '演练',
      generatedAt: '生成于',
    },
    releaseBlockers: '发布阻塞项',
    rehearsalGlobalContract: '验证演练全局契约',
    rehearsalKv: {
      status: '状态',
      targetOutcome: '目标结果',
      runbook: '操作手册',
    },
    blockingDependencies: '阻塞依赖',
    evidence: '证据',
    alertsTitle: '运行时契约告警',
    alertsEmpty: '暂无运行时契约告警。',
  },
  // 接管台
  takeover: {
    // 通用弹窗
    reasonLabel: '处置原因',
    cancelReasonLabel: '取消原因',
    propositionDescription: (id: string) => `命题 ${id || '(缺失)'}`,
    marketDescription: (marketId: string, userId: string) => `市场 ${marketId || '(缺失)'}${userId ? ` / 用户 ${userId}` : ''}`,
    globalDescription: '验证链全局动作',
    submitted: (title: string) => `${title}已提交。`,
    // 上下文摘要
    contextSummaryTitle: '上下文摘要',
    contextKv: {
      proposition: '命题',
      market: '市场',
      userOwner: '用户 / 注单归属',
      cancelReasonCode: '取消原因码',
    },
    summaryLine: (title: string, propositionStatus: string, marketStatus: string) => `${title} / 命题 ${propositionStatus} / 市场 ${marketStatus}`,
    driftKv: {
      driftReason: '漂移原因',
      chainState: '链上状态',
      operatorSummary: '运营摘要',
      runbook: '操作手册',
    },
    none: '无',
    guidedActions: '引导动作',
    plannedCommands: '计划命令',
    openPropositionWorkspace: '打开命题工作区',
    openRewardsWorkspace: '打开奖励工作区',
    openResponseQueue: '打开响应队列',
    refreshHealth: '刷新健康度',
    refreshContract: '刷新契约',
    // 命题维度
    propositionScopedTitle: '命题维度',
    propositionScopedHint: '此泳道用于处理市场生命周期漂移、缺失的指令链步骤,以及指令恢复工作。',
    propositionIdLabel: '命题 ID',
    cancelReasonInputLabel: '取消原因',
    // 市场 / 注单维度
    marketScopedTitle: '市场维度 / 注单维度',
    marketScopedHint: '此泳道用于处理结算滞留问题、未同步积压恢复、投影重放,以及单笔注单对账。',
    marketIdLabel: '市场 ID',
    userIdLabel: '用户 ID',
    stalePayoutSnapshotTitle: '结算滞留快照',
    stalePayoutSnapshotDetail: (propositionId: string, unclaimedBetCount: string, chainStatus: string) => `命题 ${propositionId} / 未认领注单 ${unclaimedBetCount} / 链 ${chainStatus}`,
    backlogSnapshotTitle: '未同步积压快照',
    backlogSnapshotDetail: (betId: string, status: string, ageSeconds: number) => `注单 ${betId} / 状态 ${status} / 已积压 ${ageSeconds} 秒`,
    operatorActions: '运营动作',
    // 全局
    globalTitle: '全局',
    globalHint: '仅当运行时契约或链健康证据明确指向全局动作时才执行这些操作。',
    globalKv: {
      runtimeSummary: '运行时摘要',
      runbook: '操作手册',
      scheduler: '调度器',
      latestEvidence: '最近证据',
    },
    loading: '加载中',
    latestEvidenceValue: (action: string, reason: string) => `${action} / ${reason}`,
    // 侧栏
    latestEvidenceTitle: '最近证据',
    recentEvidenceEmpty: '此上下文暂无近期审计证据。',
    usageGuidanceTitle: '使用指引',
    usageGuidance: [
      '尽量从命题详情、健康度或奖励工作区进入,而非手动输入原始 ID。',
      '高风险动作需填写原因,备注会随审计回执一并留存。',
      '暂停与恢复仅对 Admin 或 System 角色可见。',
    ],
  },
  // 健康度趋势卡
  trends: {
    title: '趋势线',
    hint: '基于近期健康度轮询构建,并持久化在本工作站。',
    pollPoints: (count: number) => `${count} 个轮询点`,
    sparklineAria: (title: string) => `${title}走势图`,
    steady: '与上次轮询持平',
    deltaVsPrevious: (formattedDelta: string) => `${formattedDelta} 较上次轮询`,
    waiting: {
      title: '等待趋势',
      hint: '当前队列等待积压总量',
      value: (count: string) => `${count} 等待中`,
    },
    alert: {
      title: '告警趋势',
      hint: '验证链与运行时告警合计负载',
      value: (count: string) => `${count} 活跃告警`,
    },
    anomaly: {
      title: '异常率趋势',
      hint: '活跃质量异常中的峰值异常率',
      value: (percent: string) => `${percent} 峰值异常`,
    },
    sample: {
      title: '样本进度趋势',
      hint: '有效样本朝最低阈值的完成度',
      value: (percent: string) => `${percent} 距阈值`,
    },
  },
  // 健康度注意力收件箱
  attention: {
    title: '注意力收件箱',
    criticalUnread: (count: number) => `紧急未读 ${count}`,
    unread: (count: number) => `未读 ${count}`,
    handled: (count: number) => `已处置 ${count}`,
    intro: '面向异常、样本不足与生命周期漂移的持久化运营分流。',
    empty: '当前没有待跟进的异常项。',
    statusHandled: '已处置',
    statusUnread: '未读',
    statusRead: '已读',
    openWorkspace: '打开工作区',
    markRead: '标记已读',
    markUnread: '标记未读',
    markHandled: '标记已处置',
    markUnresolved: '标记未处置',
    anomalyLabel: (title: string) => `质量异常:${title}`,
    anomalySummary: (anomalyRate: string, invalidRate: string, riskyCount: number) => `异常 ${anomalyRate},无效 ${invalidRate},高风险答题人 ${riskyCount}`,
    shortageLabel: (title: string) => `样本不足:${title}`,
    shortageSummary: (effective: number, minimum: number, shortage: number, deadlineNote: string) => `有效样本 ${effective}/${minimum},缺口 ${shortage},${deadlineNote}`,
    deadlineNearing: '临近截止',
    timeBuffer: '尚有时间余量',
    driftLabel: (title: string) => `生命周期漂移:${title}`,
    driftSummary: (driftReason: string, marketStatus: string, chainStatus: string) => `${driftReason} / 市场 ${marketStatus} / 链 ${chainStatus}`,
  },
  // 审计工作区
  audit: {
    title: '全局审计工作区',
    description: '检索面向运营的审计证据,覆盖命题、响应、奖励与验证链恢复通道。',
    showAllActors: '显示全部操作者',
    myRecentOperations: '我的近期操作',
    clearFilters: '清除筛选',
    filterSearch: '搜索',
    filterSearchPlaceholder: '动作 / 原因 / 操作者 / 实体',
    filterEntityType: '实体类型',
    filterEntityId: '实体 ID',
    filterActor: '操作者',
    filterAction: '动作',
    filterDirection: '排序方向',
    filterPageSize: '每页条数',
    directionDesc: '倒序',
    directionAsc: '正序',
    resultsTitle: '审计结果',
    resultsCount: (count: number) => `${count} 条事件`,
    empty: '没有符合当前筛选条件的审计事件。',
    kvEntity: '实体',
    kvActor: '操作者',
    actorSystem: '系统',
    filterEntityAction: '按实体筛选',
    filterActorAction: '按操作者筛选',
    previous: '上一页',
    next: '下一页',
    tipsTitle: '提示',
    tipActorAction: '先用「操作者 + 动作」筛选还原单个操作者的处置线索,再跳转到接管台或命题详情。',
    tipSearchCoverage: '搜索覆盖动作、实体、操作者、原因与备注字段,便于快速回溯事件。',
  },
  // 答题人画像
  respondent: {
    title: '答题人画像',
    reputationTitle: '信誉',
    metricScore: '信誉分',
    metricLevel: '信誉等级',
    metricRuleVersion: '规则版本',
    metricReviews: '已审响应',
    completionRate: '完成率',
    validRate: '有效率',
    partialValidRate: '部分有效率',
    invalidRate: '无效率',
    anomalyRate: '异常率',
    fraudFlags: '欺诈标记',
    tagsTitle: '标签',
    tagsEmpty: '当前没有生效的答题人标签。',
    tagHead: {
      tag: '标签',
      type: '类型',
      confidence: '置信度',
      source: '来源',
      updated: '更新时间',
    },
    rewardLedgerTitle: '奖励台账上下文',
    rewardLedgerEmpty: '未找到该答题人的奖励台账记录。',
    rewardHead: {
      ledger: '台账',
      proposition: '命题',
      status: '状态',
      pendingAmount: '待发放金额',
    },
    quickActionsTitle: '快捷操作',
    viewRewards: '查看答题人奖励',
    openTakeover: '打开人工接管',
  },
  // 派发工作台
  dispatch: {
    title: '派发工作台',
    summary: (assigned: number, submitted: number) => `已派发 ${assigned} / 已提交 ${submitted}`,
    metricActiveTasks: '进行中任务',
    metricUniqueRespondents: '去重答题人',
    metricExpired: '已过期',
    metricLastAssigned: '最近派发',
    candidateUserIds: '候选答题人 ID',
    assignedAt: '派发时间',
    expiresAt: '过期时间',
    maxAssignments: '最大派发量',
    previewDispatch: '预览派发',
    createDispatch: '创建派发',
    previewReady: (count: number) => `派发预览就绪:已选 ${count} 人`,
    created: (count: number) => `已创建 ${count} 个派发任务`,
    errorNoUserIds: '派发前至少需要填写一个候选答题人 ID。',
    errorAssignedAtRequired: '派发时间为必填项。',
    errorExpiresAtRequired: '过期时间为必填项。',
    errorMaxAssignments: '最大派发量必须为正整数。',
    previewKv: {
      ruleVersion: '规则版本',
      maxAssignments: '最大派发量',
      generalReserve: '通用储备',
      selectedUsers: '已选答题人',
    },
    selectedNone: '无',
    previewHead: {
      user: '答题人',
      eligible: '资格',
      selected: '已选',
      priority: '优先级',
      score: '评分',
      blockReason: '拦截原因',
    },
    yes: '是',
    no: '否',
  },
} as const
