export const VALID_MULTIPLIER = 1;
export const PARTIAL_VALID_MULTIPLIER = 0.5;
export const INVALID_MULTIPLIER = 0;

export const VALID_MULTIPLIER_NUMERATOR = 1n;
export const VALID_MULTIPLIER_DENOMINATOR = 1n;
export const PARTIAL_VALID_MULTIPLIER_NUMERATOR = 1n;
export const PARTIAL_VALID_MULTIPLIER_DENOMINATOR = 2n;
export const INVALID_MULTIPLIER_NUMERATOR = 0n;
export const INVALID_MULTIPLIER_DENOMINATOR = 1n;
